exit_poll_site/exit_poll_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.contrib.auth.decorators import login_required


admin.autodiscover()
admin.site.login = login_required(admin.site.login)

urlpatterns = [
    url(r'^administration/', include('administration.urls')),
    url(r'^voters/', include('voters.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^$', RedirectView.as_view(url='/account/login', permanent=False), name='index'),
]

exit_poll_site/voters/urls.py
from django.conf.urls import url

from . import views

app_name = 'voters'
urlpatterns = [
    # ex: /voters/5/
    url(r'^(?P<respondent_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<voter_id>[0-9]+)/result/$', views.result, name='result'),
    url(r'randomize/$', views.random, name='random'),
    url(r'result_instructions/$', views.result_page, name='result_page'),
    url(r'instructions/$', views.instructions, name='instructions'),
    url(r'lookup/$', views.lookup, name='lookup'),
    url(r'processvl/$', views.processvl, name='processvl'),
    url(r'lookuperror/$', views.lookuperror, name='lookuperror'),
    url(r'^(?P<voter_id>[0-9]+)/placehold/$', views.placehold, name='placehold'),
]

exit_poll_site/voters/models.py
from __future__ import unicode_literals
import datetime
from django.db import models
from django.db import models
from django.utils import timezone

class Phone(models.Model):
    phone_no = models.CharField(max_length=25)
    valid = models.BooleanField(default=True)
    user_marking_invalid = models.CharField(max_length=80, blank=True, null=True)
    #@python_2_unicode_compatible
    def __str__(self):
        return self.phone_no
    def is_valid(self):
        return self.valid

class Voter(models.Model):
    #Name
    name = models.CharField(max_length=80)
    #ID number
    respondent_id = models.CharField(max_length=25, default = None, null=True)
    #age 
    respondent_age = models.CharField(max_length=8, default = '0', null=True)
    #Spanish Speaker
    spanish_speaking = models.BooleanField(default=False)
    #Temporary Supervisor Hold
    supervisor_hold_date = models.DateTimeField('On Hold Until:', blank=True, null=True)
    #Wave
    WAVEONE = 'W1'
    WAVETWO = 'W2'
    WAVETHREE = 'W3'
    WAVEFOUR = 'W4'
    WAVE_CHOICES = (
         (WAVEONE, 'Wave One'),
         (WAVETWO, 'Wave Two'),
         (WAVETHREE, 'Wave Three'),
         (WAVEFOUR, 'Wave Four'),
    )
    respondent_wave = models.CharField(
        max_length=2,
        choices=WAVE_CHOICES,
        default=WAVEONE,
    )
    #Most Recent Display
    last_display_time = models.DateTimeField('last time of display', blank=True, null=True)
    #Call Outcomes
    TOOKSURVEY = 'TS'
    LEFTVOICEMAIL = 'LV'
    SOFTDECLINE = 'SD'
    HARDDECLINE = 'HD'
    NOTHOME = 'NH'
    REQUESTCALLBACK = 'CB'
    OUTCOME_CHOICES = (
        (TOOKSURVEY, 'Respondent took the Survey'),
        (NOTHOME, 'Not Home'),
        (REQUESTCALLBACK, 'Requested Call Back'),
        (LEFTVOICEMAIL, 'Left a Voicemail'),
        (SOFTDECLINE, 'Soft Decline'),
        (HARDDECLINE, 'Hard Decline'),
    )
    #Online Survey?
    done_online_survey = models.BooleanField(default=False)
    #Phone Numbers
    phone_no_one = models.ForeignKey(Phone, related_name='phone number one+', blank=True, null=True)
    phone_no_two = models.ForeignKey(Phone, related_name='phone number two+', blank=True, null=True)
    phone_no_three = models.ForeignKey(Phone, related_name='phone number three+', blank=True, null=True)
    #Call One Information
    call_one = models.BooleanField(default=False, blank=True)
    call_one_time = models.DateTimeField('time of first call', blank=True, null=True)
    call_one_user = models.CharField(max_length=80, blank=True, null=True)
    call_one_phone = models.OneToOneField(Phone, related_name='phone for call one+', blank=True, null=True)
    call_one_outcome = models.CharField(
        max_length=2,
        choices=OUTCOME_CHOICES,
        blank=True,
        null=True
    )
    #Call Two Information
    call_two = models.BooleanField(default=False, blank=True)
    call_two_time = models.DateTimeField('time of second call', blank=True, null=True)
    call_two_user = models.CharField(max_length=80, blank=True, null=True)
    call_two_phone = models.OneToOneField(Phone, related_name='phone for call two+', blank=True, null=True)
    call_two_outcome = models.CharField(
        max_length=2,
        choices=OUTCOME_CHOICES,
        blank=True,
        null=True
    )
    #Call Three Information
    call_three = models.BooleanField(default=False, blank=True)
    call_three_time = models.DateTimeField('time of third call', blank=True, null=True)
    call_three_user = models.CharField(max_length=80, blank=True, null=True)
    call_three_phone = models.OneToOneField(Phone, related_name='phone for call three+', blank=True, null=True)
    call_three_outcome = models.CharField(
        max_length=2,
        choices=OUTCOME_CHOICES,
        blank=True,
        null=True
    )
    #Call Four Information
    call_four = models.BooleanField(default=False, blank=True)
    call_four_time = models.DateTimeField('time of fourth call', blank=True, null=True)
    call_four_user = models.CharField(max_length=80, blank=True, null=True)
    call_four_phone = models.OneToOneField(Phone, related_name='phone for call four+', blank=True, null=True)
    call_four_outcome = models.CharField(
        max_length=2,
        choices=OUTCOME_CHOICES,
        blank=True,
        null=True
    )
    #Call Five Information
    call_five = models.BooleanField(default=False, blank=True)
    call_five_time = models.DateTimeField('time of fifth call', blank=True, null=True)
    call_five_user = models.CharField(max_length=80, blank=True, null=True)
    call_five_phone = models.OneToOneField(Phone, related_name='phone for call five+', blank=True, null=True)
    call_five_outcome = models.CharField(
        max_length=2,
        choices=OUTCOME_CHOICES,
        blank=True,
        null=True
    )
    #Call Six Information
    call_six = models.BooleanField(default=False, blank=True)
    call_six_time = models.DateTimeField('time of sixth call', blank=True, null=True)
    call_six_user = models.CharField(max_length=80, blank=True, null=True)
    call_six_phone = models.OneToOneField(Phone, related_name='phone for call six+', blank=True, null=True)
    call_six_outcome = models.CharField(
        max_length=2,
        choices=OUTCOME_CHOICES,
        blank=True,
        null=True
    )
    #Call Seven Information
    call_seven = models.BooleanField(default=False, blank=True)
    call_seven_time = models.DateTimeField('time of seventh call', blank=True, null=True)
    call_seven_user = models.CharField(max_length=80, blank=True, null=True)
    call_seven_phone = models.OneToOneField(Phone, related_name='phone for call seven+', blank=True, null=True)
    call_seven_outcome = models.CharField(
        max_length=2,
        choices=OUTCOME_CHOICES,
        blank=True,
        null=True
    )
    #Methods for getting Voter Information:
    def first_call_made(self):
        return self.call_one
    def second_call_made(self):
        return self.call_two
    def third_call_made(self):
        return self.call_three
    def fourth_call_made(self):
        return self.call_four
    def fifth_call_made(self):
        return self.call_five
    def sixth_call_made(self):
        return self.call_six
    def seventh_call_made(self):
        return self.call_seven
    def get_name(self):
        return self.name
    #@python_2_unicode_compatible
    def __str__(self):
        return self.name
    
    def is_held(self):
        if self.supervisor_hold_date is None:
            return False
        if self.supervisor_hold_date > timezone.now():
            return True
        return False
    
    #currently set to three hours
    def called_recently(self):
        if self.call_seven == True:
            if self.call_seven_time >= timezone.now() - datetime.timedelta(seconds=10800):
                return True
            else:
                return False
        if self.call_six == True:
            if self.call_six_time >= timezone.now() - datetime.timedelta(seconds=10800):
                return True
            else:
                return False
        if self.call_five == True:
            if self.call_five_time >= timezone.now() - datetime.timedelta(seconds=10800):
                return True
            else:
                return False
        if self.call_four == True:
            if self.call_four_time >= timezone.now() - datetime.timedelta(seconds=10800):
                return True
            else:
                return False
        if self.call_three == True:
            if self.call_three_time >= timezone.now() - datetime.timedelta(seconds=10800):
                return True
            else:
                return False
        if self.call_two == True:
            if self.call_two_time >= timezone.now() - datetime.timedelta(seconds=10800):
                return True
            else:
                return False
        if self.call_one == True:
            if self.call_one_time >= timezone.now() - datetime.timedelta(seconds=10800):
                return True
            else:
                return False
        return False
    
    
    def displayed_within_half_hour(self):
        if self.last_display_time == None:
            return False
        if self.last_display_time >= timezone.now() - datetime.timedelta(seconds=1800):
            return True
        return False
    
    def took_survey(self):
        if self.call_one_outcome == 'TS':
            return True
        if self.call_two_outcome == 'TS':
            return True
        if self.call_three_outcome == 'TS':
            return True
        if self.call_four_outcome == 'TS':
            return True
        if self.call_five_outcome == 'TS':
            return True
        if self.call_six_outcome == 'TS':
            return True
        if self.call_seven_outcome == 'TS':
            return True
        if self.done_online_survey:
            return True
        return False
    took_survey.boolean = True
    took_survey.short_description = 'Taken Survey Yet?'
   
    def which_call(self):
        if self.call_one == False:
            return 1
        if self.call_two == False:
            return 2
        if self.call_three == False:
            return 3
        if self.call_four == False:
            return 4
        if self.call_five == False:
            return 5
        if self.call_six == False:
            return 6
        if self.call_seven == False:
            return 7
        return 0
    
    def valid_phone(self):
        if self.phone_no_one is not None and self.phone_no_one.valid:
            return True
        if self.phone_no_two is not None and self.phone_no_two.valid:
            return True
        if self.phone_no_three is not None and self.phone_no_three.valid:
            return True
        return False
    
    def has_declined(self):
        if self.call_one:
            if self.call_one_outcome == "SD" or self.call_one_outcome == "HD":
                return True

exit_poll_site/voters/templates/voters/detail.html
{% extends "base.html" %}

{% block content%}
   
{% if user.is_staff and voter.is_held is True and not voter.call_seven and not voter.took_survey and voter.valid_phone%}

<h2><u><font color="red">Note for Supervisors:</u></h2></font>
This voter has been placed on hold until {{voter.supervisor_hold_date}} They can still be looked up, but they will not appear using
the "Make a Call" button.

<hr>
{% endif %}   

{% if not voter.call_seven and not voter.took_survey and voter.valid_phone%}  
<i>Please copy and paste this voter's ID number into Qualtrics, call them, and then record what happens below. </i>
{% endif %}

<br><br>
    
<b>Name:</b> {{ voter }} <br>
<b>ID Number / Access Code:</b> {{ voter.respondent_id }}<br>
<b>Wave:</b> {{ voter.get_respondent_wave_display }} <br>
<b>Phone Number:</b> {% if voter.get_phone_number is 1%} <i>There was an error getting a phone number. This might be becasuse all
phone numbers for this voter have been marked invalid. If you see this error, just click "Make a call" again to try a different voter.</i> {% endif %}
{% if voter.get_phone_number is not 1%} {{voter.get_phone_number.phone_no}} {% endif %}

<br><br>

{% if not voter.call_three and not voter.took_survey and voter.valid_phone%} 
{% if not voter.first_call_made%}This is the <b>first</b> call.{% endif %}
{% if voter.first_call_made and not voter.second_call_made %}This is the <b>second</b> call. <br><br>{% endif %}
{% if voter.first_call_made and voter.second_call_made and not voter.third_call_made %}This is the <b>third</b> call. <br><br>{% endif %}
{% endif %}

{% if voter.first_call_made%} <b><u>First Call Information:</b></u> <br>
<b>Time of First Call:</b> {{voter.call_one_time}} <br>
<b>User Who Made the First Call:</b> {{voter.call_one_user}} <br>
<b>First Call Outcome:</b> {{voter.get_call_one_outcome_display}}
{% endif %}

{% if voter.second_call_made%} <br><br><b><u>Second Call Information:</b></u> <br>
<b>Time of Second Call:</b> {{voter.call_two_time}} <br>
<b>User Who Made the Second Call:</b> {{voter.call_two_user}} <br>
<b>Second Call Outcome:</b> {{voter.get_call_two_outcome_display}}
{% endif %}

{% if voter.third_call_made%} <br><br><b><u>Third Call Information:</b></u> <br>
<b>Time of Third Call:</b> {{voter.call_three_time}} <br>
<b>User Who Made the Third Call:</b> {{voter.call_three_user}} <br>
<b>Third Call Outcome:</b> {{voter.get_call_three_outcome_display}}
{% endif %}

{% if voter.fourth_call_made%} <br><br><b><u>Fourth Call Information:</b></u> <br>
<b>Time of Fourth Call:</b> {{voter.call_four_time}} <br>
<b>User Who Made the Fourth Call:</b> {{voter.call_four_user}} <br>
<b>Fourth Call Outcome:</b> {{voter.get_call_four_outcome_display}}
{% endif %}

{% if voter.fifth_call_made%} <br><br><b><u>Fifth Call Information:</b></u> <br>
<b>Time of Fifth Call:</b> {{voter.call_five_time}} <br>
<b>User Who Made the Fifth Call:</b> {{voter.call_five_user}} <br>
<b>Fifth Call Outcome:</b> {{voter.get_call_five_outcome_display}}
{% endif %}

{% if voter.sixth_call_made%} <br><br><b><u>Sixth Call Information:</b></u> <br>
<b>Time of Sixth Call:</b> {{voter.call_six_time}} <br>
<b>User Who Made the Sixth Call:</b> {{voter.call_six_user}} <br>
<b>Sixth Call Outcome:</b> {{voter.get_call_six_outcome_display}}
{% endif %}

{% if voter.seventh_call_made%} <br><br><b><u>Seventh Call Information:</b></u> <br>
<b>Time of Seventh Call:</b> {{voter.call_seven_time}} <br>
<b>User Who Made the Seventh Call:</b> {{voter.call_seven_user}} <br>
<b>Seventh Call Outcome:</b> {{voter.get_call_seven_outcome_display}}
{% endif %}


{% if not voter.call_seven and not voter.took_survey and voter.valid_phone%} 
<br><br>
<u>What happened when you called this voter? </u><br> <br> 

<form action="{% url 'voters:result' voter.id %}" method="post">
{% csrf_token %}
    <input type="radio" name="result" id="Took Survey" value="TS" />
    <label for="TS"> The voter <b>took the survey.</b> </label><br /><br>
    
    <input type="radio" name="result" id="Not Home" value="NH" />
    <label for="NH"> The voter <b>wasn't home</b> and you <i>didn't</i> leave a voicemail. </label><br /><br>
    
    <input type="radio" name="result" id="Left Voicemail" value="LV" />
    <label for="LV"> The voter wasn't home and you <i>did</i> leave a <b>voicemail.</b> </label><br /><br>
    
    <input type="radio" name="result" id="Requested Callback" value="CB" />
    <label for="RC"> The voter requested a <b>call back</b> at another time.** </label><br /><br>
    
    <input type="radio" name="result" id="Soft Decline" value="SD" />
    <label for="SD"> The voter <b>declined</b> to take the survey. (Soft Decline) </label><br /><br>
    
    <input type="radio" name="result" id="Hard Decline" value="HD" />
    <label for="HD"> The voter <b><i>adamantly</i> declined</b> to take the survey. (Hard Decline) </label><br /><br>
    
    <input type="radio" name="result" id="Disconnected" value="DC" />
    <label for="DC"> This was an <b>invalid phone number</b>. (Wrong number, disconnected, not in service, etc.) </label>
<br><br>
<input type="submit" value="Submit" />
</form>
<br>** If the voter requested a callback at a specific time, please note their name and ID number before clicking "submit"
and give that information to the supervisor. Voters can only be called while phone banks are open (3-9pm on weekdays, 9am-9pm
on Saturdays.)<br><br>
{% endif %}


{% if user.is_staff and voter.is_held is False and not voter.call_seven and not voter.took_survey and voter.valid_phone%}

<hr>

<h2><u>Supervisor Tools: Place a Temporary Hold*</u></h2>
<form action="{% url 'voters:placehold' voter.id %}" method="post">
{% csrf_token %}
    <input type="radio" name="hold" id="One Day" value="1" />
    <label for="1">One Day (24 Hour) Hold</label><br />
    
    <input type="radio" name="hold" id="Two Day" value="2" />
    <label for="2">Two Day (48 Hour) Hold </label><br />
    
    <input type="radio" name="hold" id="Three Day" value="3" />
    <label for="3">Three Day (72 Hour) Hold</label><br />
    
    <input type="radio" name="hold" id="Four Day" value="4" />
    <label for="4">Four Day (96 Hour) Hold</label><br />
    
    <input type="radio" name="hold" id="Five Day" value="5" />
    <label for="5">Five Day (120  Hour) Hold</label><br />
    
    <input type="radio" name="hold" id="Six Day" value="6" />
    <label for="6">Six Day (144 Hour) Hold</label><br />
    
    <input type="radio" name="hold" id="Seven Day" value="7" />
    <label for="7">Seven Day (178 Hour) Hold</label>
<br><br>
<input type="submit" value="Place Hold" /><br><br>

*Placing a hold doesn't prevent a person from being called via the "lookup" function; it only prevents them from being placed in the
pool of people to be called with the "Make A Call" button. Place a hold on someone if they request a callback at a certain time to make sure they aren't
called sooner than they requested.
{% endif %}


  
  
{% endblock content%}

exit_poll_site/voters/templates/voters/error.html
{% extends "base.html" %}

{% block content%}
According to the database, there are no calls to be made right now. This is likely an error - please contact the supervisor.
{% endblock content%}

exit_poll_site/voters/templates/voters/index.html
{% if voter_list %}
    <ul>
    {% for voter in voter_list %}
        <li><a href="/voters/{{ voter.id }}/">{{ voter.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No voters have are registered in the system.</p>
{% endif %}

exit_poll_site/voters/templates/voters/instructions.html
{% extends "base.html" %}

{% block content%}
<h2>Instructions</h2>
(If this is your first time logging in, go to "Account" and change your password before following these steps.)<br><br>
<ol>
    <li>Go to exitpollhours.byu.edu and clock in. This is what we use to determine the extra credit we report to your professor.</li><br><br>
    <li>Open the Qualtrics survey (link in the navigation bar above) in a new tab.</li><br><br>
    <li>When you are ready, click the "Make a Call" button above.</li><br><br>
    <li>Copy and paste the voter's ID Number into the Qualtrics Survey. (<u>Important:</u> Copy and paste the voter's
    ID number, do not type it out. The ID number must be <u>exactly</u> right for the data to be useful to us.</li><br><br><br>
    <li>After you've entered the voter's ID number into Qualtrics, call the voter and follow the script to ask for
    their participation.</li><br><br>
    <li>After the call ends, come back to this system and record what happened when you called the voter.</li><br><br>
    
    <br><br><br>
    <b>Remember:</b> Do everything you can, while respecting the voluntary nature of the survey, to resolve voter's concerns and
    help them feel comfertable taking the survey. <i>For every voter that declines to take the survey, our data becomes less
    accurate.</i>
    <br><br>
    Don't forget: this survey is <b>voluntary</b>, <b>anonymous</b>, and the answers will be kept
    <b>confidential</b>.
</ol>
{% endblock content%}

exit_poll_site/voters/templates/voters/lookup.html
{% extends "base.html" %}

{% block content%}

<h2>Lookup A Voter</h2>

<i>You should only use this page if a supervisor directs you to do so.</i>
<br><br><br>
<form action="{% url 'voters:processvl' %}" method="post">
    {% csrf_token %}
    <div >
        <label for='voter_id'> Voter's ID Number: </label>
        <input type='text' name='voter_id' id='voter_id'> <br><br>
        <input type='submit' value='Look Up Voter'>
    </div>
</form>

{% endblock content%}

exit_poll_site/voters/templates/voters/lookuperror.html
{% extends "base.html" %}

{% block content%}

<h2>Lookup A Voter</h2>


<font color = "red">Sorry, there was an error.</font> Are you sure a voter with that ID number exists? <br><br>

<a href="{% url 'voters:lookup' %}">Try Again</a>

{% endblock content%}

exit_poll_site/voters/templates/voters/result_page.html
{% extends "base.html" %}

{% block content%}

Thank you! This call has been recorded. To make another call, click the "Make a Call" button above. If this was your last call,
please remember to log out.

{% endblock content%}