exit_poll_site/account/urls.py
from django.conf.urls import url

from . import views

app_name = 'account'
urlpatterns = [
    url(r'login/$', views.login, name='login'),
    url(r'authenticate/$', views.authenticate, name='authenticate'),
    url(r'loginfail/$', views.loginfail, name='loginfail'),
    url(r'logout/$', views.logout, name='logout'),
    url(r'accountdetail/$', views.accountdetail, name='accountdetail'),
    url(r'changepassword/$', views.changepassword, name='changepassword'),
    url(r'changefail/$', views.changefail, name='changefail'),

]

exit_poll_site/administration/urls.py
from django.conf.urls import url

from . import views

app_name = 'administration'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

exit_poll_site/exit_poll_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.contrib.auth.decorators import login_required


admin.autodiscover()
admin.site.login = login_required(admin.site.login)

urlpatterns = [
    url(r'^administration/', include('administration.urls')),
    url(r'^voters/', include('voters.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^$', RedirectView.as_view(url='/account/login', permanent=False), name='index'),
]

exit_poll_site/voters/urls.py
from django.conf.urls import url

from . import views

app_name = 'voters'
urlpatterns = [
    # ex: /voters/5/
    url(r'^(?P<respondent_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<voter_id>[0-9]+)/result/$', views.result, name='result'),
    url(r'randomize/$', views.random, name='random'),
    url(r'result_instructions/$', views.result_page, name='result_page'),
    url(r'instructions/$', views.instructions, name='instructions'),
    url(r'lookup/$', views.lookup, name='lookup'),
    url(r'processvl/$', views.processvl, name='processvl'),
    url(r'lookuperror/$', views.lookuperror, name='lookuperror'),
    url(r'^(?P<voter_id>[0-9]+)/placehold/$', views.placehold, name='placehold'),
]

exit_poll_site/templates/base.html
<!DOCTYPE html>
    
<head>
<title>UCEP Contact Generator</title>
<script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<html lang="en">
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #0B0694;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li b {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

a:hover:not(.active) {
    background-color: #940648;
}


</style>
<body>

<ul>
  <li><b>UCEP 2016 Contact Generator</b></li>
  {% if user.is_authenticated %} 
  <li><a href="{% url 'voters:instructions' %}">Instructions</a></li>
  <li><a href="https://byu.az1.qualtrics.com/SE/?SID=SV_0PnCqqbkg0nv9J3" target="_blank">Qualtrics Survey</a></li>
  <li><a href="{% url 'voters:random' %}">Make a Call &#x260E</a></li>
  <li><a href="{% url 'voters:lookup' %}">Lookup a Voter</a></li>
  <li><a href="{% url 'account:accountdetail' %}">Account ({{user.get_full_name}})</a></li>
  {% if user.is_staff %} 
  <li><a href="{% url 'administration:index' %}">Supervisors</a></li>
  {% endif %} 
  <li><a href="{% url 'account:logout' %}">Logout</a></li>
  {% endif %} 
</ul>
</body>
<br>{% block content %}{% endblock %}
</html>