exit_poll_site/account/urls.py
from django.conf.urls import url

from . import views

app_name = 'account'
urlpatterns = [
    url(r'login/$', views.login, name='login'),
    url(r'authenticate/$', views.authenticate, name='authenticate'),
    url(r'loginfail/$', views.loginfail, name='loginfail'),
    url(r'logout/$', views.logout, name='logout'),
    url(r'accountdetail/$', views.accountdetail, name='accountdetail'),
    url(r'changepassword/$', views.changepassword, name='changepassword'),
    url(r'changefail/$', views.changefail, name='changefail'),

]

exit_poll_site/exit_poll_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.contrib.auth.decorators import login_required


admin.autodiscover()
admin.site.login = login_required(admin.site.login)

urlpatterns = [
    url(r'^administration/', include('administration.urls')),
    url(r'^voters/', include('voters.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^$', RedirectView.as_view(url='/account/login', permanent=False), name='index'),
]

exit_poll_site/voters/urls.py
from django.conf.urls import url

from . import views

app_name = 'voters'
urlpatterns = [
    # ex: /voters/5/
    url(r'^(?P<respondent_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<voter_id>[0-9]+)/result/$', views.result, name='result'),
    url(r'randomize/$', views.random, name='random'),
    url(r'result_instructions/$', views.result_page, name='result_page'),
    url(r'instructions/$', views.instructions, name='instructions'),
    url(r'lookup/$', views.lookup, name='lookup'),
    url(r'processvl/$', views.processvl, name='processvl'),
    url(r'lookuperror/$', views.lookuperror, name='lookuperror'),
    url(r'^(?P<voter_id>[0-9]+)/placehold/$', views.placehold, name='placehold'),
]

exit_poll_site/account/forms.py
from django import forms
from captcha.fields import ReCaptchaField

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()
    captcha = ReCaptchaField()

exit_poll_site/account/views.py
from django.shortcuts import render, get_object_or_404
from datetime import datetime   
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from random import randrange
from django.contrib.auth import authenticate as auth
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from account.forms import LoginForm
from django.views.generic.edit import FormView
from django import forms
import requests
from recaptcha.client import captcha
from requests.auth import HTTPDigestAuth
import json

def valid_captcha(challenge_field, response_field, private_key):
    url = "https://www.google.com/recaptcha/api/siteverify"
    data = {'secret': '6Lf7OwkUAAAAAKaoIgla6_Iwob5Y8PWwwmqGqeZn', 'response':response_field}
    response = requests.post(url, data=data)
    r = response.json()
    return r['success']


def login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/voters/instructions/')
    return render (request, 'login.html')

    
def authenticate(request):
    usern = request.POST.get('Username', '')
    passw = request.POST.get('Password', '')
    captcha_response = request.POST.get('g-recaptcha-response','')
    captcha_check = valid_captcha(captcha_response, captcha_response, "6Lf7OwkUAAAAAKaoIgla6_Iwob5Y8PWwwmqGqeZn")
    if captcha_check == True:
        user = auth(username = usern, password = passw)      
        if user is not None:
            auth_login(request, user)
            return HttpResponseRedirect('/voters/instructions')
        else:
            return HttpResponseRedirect('/account/loginfail')
    else:
        return HttpResponseRedirect('/account/loginfail')

def loginfail(request):
    return render (request, 'loginfail.html')

def logout(request):
    auth_logout(request)
    return HttpResponseRedirect('/account/login')

@login_required
def accountdetail(request):
    return render (request, 'accountdetail.html')

@login_required
def changepassword(request):
    pass1 = request.POST.get('password1', '')
    pass2 = request.POST.get('password2', '')
    if pass1 == pass2 and pass1 != "":
        request.user.set_password(pass1)
        request.user.save()
        auth_logout(request)
        return HttpResponseRedirect('/account/login')
    else:
        return HttpResponseRedirect('/account/changefail')

@login_required    
def changefail(request):
    return render (request, 'changefail.html')

exit_poll_site/account/templates/accountdetail.html
{% extends "base.html" %}

{% block content%}
<h2>Account Details</h2>
<b>First Name:</b> {{user.get_short_name}}<br><br>
<b>Last Name:</b> {{user.last_name}}<br><br>
<b>Net ID:</b> {{user.get_username}}<br><br>
<b>Email Address:</b> {{user.email}}<br><br>

<i>If any of the above information is incorrect, please speak to a supervisor.</i><br><br>

<h2>Change Password</h2>
To change your password, please use the form below. Note that changing your password will log you out, and you will need to log
in again. <br><br>

<form action="{% url 'account:changepassword' %}" method="post">
    {% csrf_token %}
    <div >
        <label for='password1'> Enter Your New Password: </label>
        <input type='password' name='password1' id='password1'> <br><br>
        <label for='password2'>Confrm Your Password:  </label>
        <input type='password' name='password2' id='password2'><br><br>
        <input type='submit' value='Change Password'>
    </div>
</form>

{% endblock content%}

exit_poll_site/account/templates/changefail.html
{% extends "base.html" %}

li a {
}

a:hover:not(.active) {
}


{% block content%}
    Sorry, there was an error. Are you sure the two password fields matched? <a href="{% url 'account:accountdetail' %}">Click here</a> to try again.
{% endblock content%}

exit_poll_site/account/templates/login.html
{% extends "base.html" %}

{% block content%}
    
<h2>Welcome! Please login to continue.</h2> <br>
<form action="{% url 'account:authenticate' %}" method="post">
    {% csrf_token %}
    <div >
        <label for='username'> Username: </label>
        <input type='text' name='Username' id='username'> <br><br>
        <label for='password'>Password:  </label>
        <input type='password' name='Password' id='password'><br><br>
        <div class="g-recaptcha" data-sitekey="6Lf7OwkUAAAAAA6I_IkDsyaZtuCUvMNufvfd4Vra"></div><br>
        <input type='submit' value='Login'>
    </div>
</form>


<br><br> <i>If this is your first time logging in, your username is your Net Id and your password is your student ID number
exactly as you entered it in the volunteer form. If you cannot remember your password, please speak to a supervisor. If
this is your first time logging in, remember to change your password when you login.</i>

<br><br>
v1.2
{% endblock content%}

exit_poll_site/account/templates/loginfail.html
{% extends "base.html" %}

{% block content%}
    
<h2><font color = "red">There was an error. Are you sure the username and password were correct?</font></h2> <br>
<form action="{% url 'account:authenticate' %}" method="post">
    {% csrf_token %}
    <div >
        <label for='username'> Username: </label>
        <input type='text' name='Username' id='username'> <br><br>
        <label for='password'>Password:  </label>
        <input type='password' name='Password' id='password'><br><br>
        <div class="g-recaptcha" data-sitekey="6Lf7OwkUAAAAAA6I_IkDsyaZtuCUvMNufvfd4Vra"></div><br>
        <input type='submit' value='Login'>
    </div>
</form>


<br><br> <i>If this is your first time logging in, your username is your Net Id and your password is your student ID number
exactly as you entered it in the volunteer form. If you cannot remember your password, please speak to a supervisor. If
this is your first time logging in, remember to change your password when you login.</i>

<br><br>
v1.2
{% endblock content%}